apiVersion: v1
kind: Template
objects:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: $(NAME)
      labels:
        jobgroup: indexing
    spec:
      template:
        metadata:
          name: $(NAME)
          labels:
            jobgroup: indexing
        spec:
          containers:
          - name: c
            image: eu.gcr.io/kbh-billeder/frontend:$(BRANCH)-latest
            imagePullPolicy: Always
            command: ["npm", "run", "index", "--", $(MODE), $(EXTRA), $(EXTRA_2)]
            env:
            - name: ES_HOST
              value: "elasticsearch:9200"
            - name: MONGO_CONNECTION
              value: "mongodb://mongo:27017/kbh-billeder"
          restartPolicy: Never
parameters:
  - name: BRANCH
    description: The branch from which the image should be derived
    required: true
  - name: NAME
    description: The name of the index job
    required: true
  - name: MODE
    description: The mode in which to run the indexing
    required: true
  - name: EXTRA
    description: The reference or extra runtime arguments
    required: false
  - name: EXTRA_2
    description: Another extra runtime argument
    required: false
