version: '3.5'
services:
  elasticsearch:
    image: elasticsearch:7.16.3
    volumes:
      - 'esdata:/usr/share/elasticsearch/data'
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node

  mongo:
    image: mongo:3.5.6
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017

  node:
    build:
      context: .
    command: npm start
    ports:
      - 9000:9000
    volumes:
      - .:/app
    depends_on:
      - elasticsearch
      - mongo
    links:
      - mongo
      - elasticsearch
    environment:
      NODE_ENV: development

volumes:
  esdata:
    driver: local
  mongodata:
