apiVersion: v1
kind: Template
objects:
  - apiVersion: v1
    kind: ReplicationController
    metadata:
      name: mongo
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            component: mongo
        spec:
          containers:
          - name: mongo
            image: mongo:3.6
            ports:
            - containerPort: 27017
              name: http
              protocol: TCP
            volumeMounts:
              - name: mongo-storage
                mountPath: /data/db
          volumes:
          - name: mongo-storage
            gcePersistentDisk:
              pdName: $(MONGO_DISK_NAME)
              fsType: ext4
parameters:
  - name: MONGO_DISK_NAME
    description: The name of the mongo disk
    required: true
